services:
  app:
    build:
      context: .
      dockerfile: packages/backend/infra/Dockerfile
    restart: always
    ports:
      - "3000:3000/tcp"
    networks:
      - external_network
    env_file:
      - packages/backend/.env

  redis:
    restart: always
    image: redis:7.2.4-alpine
    networks:
      - internal_network
    volumes:
      - redis:/data
    healthcheck:
      test: "redis-cli ping"
      interval: 5s
      retries: 20

  db:
    restart: always
    image: postgres:16.1-bookworm
    networks:
      - internal_network
    env_file:
      - packages/backend/.env
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
      interval: 5s
      retries: 20

volumes:
    redis:
    postgres:

networks:
  external_network:
  internal_network:
